/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package orgmode

fun main(args: Array<String>) {

    val org: Org = OrgParser(StringSource("""
* 1
* 5
- List
  123
1. Also list






   abs
2.Not list
Test 5
** 6
Test 5""")).parse()

    println(org.toString())
    println(org.toJson())
    println(org.toHtml())
}
