/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package orgmode

fun main(args: Array<String>) {

    val org: Org = OrgParser(StringSource("""
* 1
Test 1
** 2
Test 2
** 3
Test 3
*** 4
Test 4
* 5
Test 5
** 6
Test 5""")).parse()

    println(org.toString())
    println(org.toJson())
}
